name: rdcli_ui
description: "A frontend for RDCLI."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  rdcli:
    git: https://github.com/tytydraco/rdcli
  shared_objects:
    git: https://github.com/tytydraco/shared_objects

dev_dependencies:
  basil:
    git: https://github.com/tytydraco/basil
  flutter_test:
    sdk: flutter
  icons_launcher: ^2.0.5
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true

icons_launcher:
  image_path: 'assets/icon.png'
  platforms:
    android:
      enable: true
    ios:
      enable: true
    macos:
      enable: true
    windows:
      enable: true
    web:
      enable: true
    linux:
      enable: true