name: rdcli_ui
description: "A frontend for RDCLI."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  rdcli:
    git: https://github.com/tytydraco/rdcli
  shared_objects:
    git: https://github.com/tytydraco/shared_objects

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
